### ISSUE TITLE
Autoloading Error

### ISSUE THREAD

**Issue by pepin82** [ziollek/PAXB#1]
@ziollek,

There is a problem with the autoloading, the composer.json file is currently like this:

`"autoload": {
        "psr-4": {"PAXB\\": "src/"}
    }`

and it should be like that:

`"autoload": {
        "psr-4": {"PAXB\\": "src/PAXB"}
    }`

could you please fix it,

thanks in advance

**Comment by ziollek** [comment]
As i see there is psr-0:

```
"autoload": {
    "psr-0": {"PAXB": "lib/"}
}
```

**Comment by pepin82** [comment]
@ziollek ,

I was looking a fork of your code, that is register on packagist [https://packagist.org/search/?q=publib%2FPAXB](url), that have an error on composer.json. Sorry for the inconvenience
